# Generated by Django 3.0.6 on 2020-06-01 21:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_populate_uuid_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
