# Generated by Django 3.0.6 on 2020-06-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_remove_uuid_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancel_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Pending'), ('paid', 'Paid'), ('uncollectible', 'Uncollectible'), ('void', 'Void')], max_length=25),
        ),
    ]
