# Generated by Django 3.0.6 on 2020-05-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20200522_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='place_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
