# Generated by Django 3.0.6 on 2020-05-23 23:32

import companies.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20200523_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cover_img',
            field=models.FileField(blank=True, null=True, storage=companies.storage_backends.CoverImageMediaStorage(), upload_to=''),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, null=True, storage=companies.storage_backends.ProfileImageMediaStorage(), upload_to=''),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_background_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
