# Generated by Django 3.0.6 on 2020-05-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('DL', 'Delinquent'), ('SU', 'Signing Up'), ('SB', 'Subscribed'), ('EX', 'Example')], default='SU', max_length=2),
        ),
    ]
