# Generated by Django 3.0.6 on 2020-06-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_auto_20200602_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='trial_period',
            field=models.BooleanField(default=True),
        ),
    ]
