# Generated by Django 3.0.6 on 2020-06-04 12:56

import companies.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_company_trial_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='flyer',
            field=models.FileField(blank=True, null=True, storage=companies.storage_backends.FlyerMediaStorage(), upload_to=''),
        ),
    ]
