# Generated by Django 3.0.6 on 2020-06-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_company_flyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='safety_policy_setting',
            field=models.CharField(choices=[('B', 'Basic'), ('C', 'Form Checkbox'), ('P', 'Pop Up'), ('CP', 'Custom Pop Up')], default='B', max_length=2),
        ),
    ]
