# Generated by Django 3.0.6 on 2020-06-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_company_safety_policy_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='safety_policy_setting',
            field=models.CharField(choices=[('B', 'Basic'), ('F', 'Form Checkbox'), ('P', 'Popup'), ('CP', 'Custom Pop Up')], default='B', max_length=2, verbose_name='Safety Policy Setting'),
        ),
    ]
