# Generated by Django 3.0.6 on 2020-06-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_auto_20200606_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='safety_policy_setting',
            field=models.CharField(choices=[('B', 'Basic'), ('CB', 'Custom Basic'), ('F', 'Form Checkbox'), ('CF', 'Custom Form Checkbox'), ('P', 'Popup'), ('CP', 'Custom Pop Up')], default='B', max_length=2, verbose_name='Safety Policy Setting'),
        ),
    ]
