# Generated by Django 3.0.6 on 2020-05-24 08:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import track.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_auto_20200523_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('submitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmation', models.CharField(default=track.models.confirmation_code_generator, max_length=6)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='US')),
                ('arrival', models.DateTimeField(default=django.utils.timezone.now)),
                ('departure', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.Company')),
            ],
        ),
    ]
