# Generated by Django 3.0.6 on 2020-06-06 16:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_auto_20200606_1224'),
        ('track', '0003_auto_20200605_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSafetyPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('policy_text', models.TextField()),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety_policy', to='companies.Company')),
            ],
        ),
    ]
